package com.csair.b2c.cloud.test.sys.cbd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-08-27T14:42:39.259+08:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://web.service.newccs.cbd.csair.com", name = "NEWCBDCCSWebServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface NEWCBDCCSWebServicePortType {

    @WebMethod
    @RequestWrapper(localName = "queryRecruitByMemberNo", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryRecruitByMemberNo")
    @ResponseWrapper(localName = "queryRecruitByMemberNoResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryRecruitByMemberNoResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public ArrayOfRecruitDto queryRecruitByMemberNo(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryFlightSegment", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryFlightSegment")
    @ResponseWrapper(localName = "queryFlightSegmentResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryFlightSegmentResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public ArrayOfFlightSegmentDto queryFlightSegment(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            javax.xml.datatype.XMLGregorianCalendar in1,
            @WebParam(name = "in2", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in3,
            @WebParam(name = "in4", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in4
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryExchangeByFQU", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryExchangeByFQU")
    @ResponseWrapper(localName = "queryExchangeByFQUResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryExchangeByFQUResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public QueryPriceResultDto queryExchangeByFQU(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            ArrayOfQueryPriceDto in1,
            @WebParam(name = "in2", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in3,
            @WebParam(name = "in4", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in4,
            @WebParam(name = "in5", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in5,
            @WebParam(name = "in6", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            int in6
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "hasEnabledPassword", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.HasEnabledPassword")
    @ResponseWrapper(localName = "hasEnabledPasswordResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.HasEnabledPasswordResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public String hasEnabledPassword(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryMemberInfoForVOSNew", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMemberInfoForVOSNew")
    @ResponseWrapper(localName = "queryMemberInfoForVOSNewResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMemberInfoForVOSNewResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public MemberExchangeInfoForVOSNewDto queryMemberInfoForVOSNew(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryMemberInfoForVOS", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMemberInfoForVOS")
    @ResponseWrapper(localName = "queryMemberInfoForVOSResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMemberInfoForVOSResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public MemberExchangeInfoForVOSDto queryMemberInfoForVOS(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "checkExchangeStandardForVOS", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.CheckExchangeStandardForVOS")
    @ResponseWrapper(localName = "checkExchangeStandardForVOSResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.CheckExchangeStandardForVOSResponse")
    public void checkExchangeStandardForVOS(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryMemberInfoForB2CWithJoinDate", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMemberInfoForB2CWithJoinDate")
    @ResponseWrapper(localName = "queryMemberInfoForB2CWithJoinDateResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMemberInfoForB2CWithJoinDateResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public MemberInfoForB2CDto queryMemberInfoForB2CWithJoinDate(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryExchangeStandFor2015", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryExchangeStandFor2015")
    @ResponseWrapper(localName = "queryExchangeStandFor2015Response", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryExchangeStandFor2015Response")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public MobileExchangeStandDtoFor2015 queryExchangeStandFor2015(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in2
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryMemberDetailInfoForVOS", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMemberDetailInfoForVOS")
    @ResponseWrapper(localName = "queryMemberDetailInfoForVOSResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMemberDetailInfoForVOSResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public MemberInfoForVOS queryMemberDetailInfoForVOS(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isAuthorizedCmd", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.IsAuthorizedCmd")
    @ResponseWrapper(localName = "isAuthorizedCmdResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.IsAuthorizedCmdResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public boolean isAuthorizedCmd(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in3,
            @WebParam(name = "in4", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in4
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "preSingleRecruitCheckFreeAndDe", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.PreSingleRecruitCheckFreeAndDe")
    @ResponseWrapper(localName = "preSingleRecruitCheckFreeAndDeResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.PreSingleRecruitCheckFreeAndDeResponse")
    public void preSingleRecruitCheckFreeAndDe(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            RecruitApplyDto in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            boolean in1,
            @WebParam(name = "in2", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            boolean in2,
            @WebParam(name = "in3", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            boolean in3
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryMemberInfoForB2C", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMemberInfoForB2C")
    @ResponseWrapper(localName = "queryMemberInfoForB2CResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMemberInfoForB2CResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public MemberExchangeInfoForB2CDto queryMemberInfoForB2C(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryExchangeStandForBM", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryExchangeStandForBM")
    @ResponseWrapper(localName = "queryExchangeStandForBMResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryExchangeStandForBMResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public MobileExchangeStandDto queryExchangeStandForBM(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in2
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "commandFxe", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.CommandFxe")
    @ResponseWrapper(localName = "commandFxeResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.CommandFxeResponse")
    public void commandFxe(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in3,
            @WebParam(name = "in4", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in4,
            @WebParam(name = "in5", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in5,
            @WebParam(name = "in6", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in6,
            @WebParam(name = "in7", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            int in7
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "commandFrb", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.CommandFrb")
    @ResponseWrapper(localName = "commandFrbResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.CommandFrbResponse")
    public void commandFrb(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in3,
            @WebParam(name = "in4", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in4,
            @WebParam(name = "in5", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in5,
            @WebParam(name = "in6", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in6,
            @WebParam(name = "in7", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            int in7
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findMemberServiceInfoFromMbTips", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.FindMemberServiceInfoFromMbTips")
    @ResponseWrapper(localName = "findMemberServiceInfoFromMbTipsResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.FindMemberServiceInfoFromMbTipsResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public ArrayOfMbTipsDto findMemberServiceInfoFromMbTips(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryMileageStandardByDate", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMileageStandardByDate")
    @ResponseWrapper(localName = "queryMileageStandardByDateResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMileageStandardByDateResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public ArrayOfMileageStandardDto queryMileageStandardByDate(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            javax.xml.datatype.XMLGregorianCalendar in2
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryTravelRecordByTicketNumber", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryTravelRecordByTicketNumber")
    @ResponseWrapper(localName = "queryTravelRecordByTicketNumberResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryTravelRecordByTicketNumberResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public ArrayOfFlightSegmentDto queryTravelRecordByTicketNumber(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "closeExchangeByEOT", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.CloseExchangeByEOT")
    @ResponseWrapper(localName = "closeExchangeByEOTResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.CloseExchangeByEOTResponse")
    public void closeExchangeByEOT(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in3,
            @WebParam(name = "in4", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in4,
            @WebParam(name = "in5", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            int in5
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "countPsgTravelTimes", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.CountPsgTravelTimes")
    @ResponseWrapper(localName = "countPsgTravelTimesResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.CountPsgTravelTimesResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public ArrayOfTravelCountDto countPsgTravelTimes(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            javax.xml.datatype.XMLGregorianCalendar in1,
            @WebParam(name = "in2", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            javax.xml.datatype.XMLGregorianCalendar in2
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findPasswordByBindEmail", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.FindPasswordByBindEmail")
    @ResponseWrapper(localName = "findPasswordByBindEmailResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.FindPasswordByBindEmailResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public String findPasswordByBindEmail(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in1
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "quickEnrollMemberForCoop", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QuickEnrollMemberForCoop")
    @ResponseWrapper(localName = "quickEnrollMemberForCoopResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QuickEnrollMemberForCoopResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public QuickEnrollInfoReturnDto quickEnrollMemberForCoop(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in3,
            @WebParam(name = "in4", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in4,
            @WebParam(name = "in5", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in5,
            @WebParam(name = "in6", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in6,
            @WebParam(name = "in7", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in7,
            @WebParam(name = "in8", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in8,
            @WebParam(name = "in9", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in9,
            @WebParam(name = "in10", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in10,
            @WebParam(name = "in11", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in11,
            @WebParam(name = "in12", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in12,
            @WebParam(name = "in13", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in13,
            @WebParam(name = "in14", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in14,
            @WebParam(name = "in15", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            javax.xml.datatype.XMLGregorianCalendar in15,
            @WebParam(name = "in16", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in16
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "commandFtu", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.CommandFtu")
    @ResponseWrapper(localName = "commandFtuResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.CommandFtuResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public FtuResutlDto commandFtu(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in1,
            @WebParam(name = "in2", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in2,
            @WebParam(name = "in3", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in3,
            @WebParam(name = "in4", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            int in4,
            @WebParam(name = "in5", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in5,
            @WebParam(name = "in6", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in6,
            @WebParam(name = "in7", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            ArrayOfQueryPriceDto in7,
            @WebParam(name = "in8", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in8,
            @WebParam(name = "in9", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in9,
            @WebParam(name = "in10", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in10,
            @WebParam(name = "in11", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in11,
            @WebParam(name = "in12", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in12,
            @WebParam(name = "in13", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in13,
            @WebParam(name = "in14", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            int in14
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findPasswordByBindPhone", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.FindPasswordByBindPhone")
    @ResponseWrapper(localName = "findPasswordByBindPhoneResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.FindPasswordByBindPhoneResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public String findPasswordByBindPhone(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in1
    ) throws WebServiceException_Exception;

    @WebMethod
    @RequestWrapper(localName = "queryMileageStandard", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMileageStandard")
    @ResponseWrapper(localName = "queryMileageStandardResponse", targetNamespace = "http://web.service.newccs.cbd.csair.com", className = "com.csair.b2c.cloud.test.sys.picc.QueryMileageStandardResponse")
    @WebResult(name = "out", targetNamespace = "http://web.service.newccs.cbd.csair.com")
    public ArrayOfMileageStandardDto queryMileageStandard(
            @WebParam(name = "in0", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in0,
            @WebParam(name = "in1", targetNamespace = "http://web.service.newccs.cbd.csair.com")
            String in1
    ) throws WebServiceException_Exception;
}
