package com.csair.b2c.cloud.test.sys.cbd;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-08-27T14:42:39.296+08:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "NEWCBDCCSWebService",
                  wsdlLocation = "http://10.79.0.101:8180/CBDCCSWebService/services/NEWCBDCCSWebService?wsdl",
                  targetNamespace = "http://web.service.newccs.cbd.csair.com")
public class NEWCBDCCSWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://web.service.newccs.cbd.csair.com", "NEWCBDCCSWebService");
    public final static QName NEWCBDCCSWebServiceHttpPort = new QName("http://web.service.newccs.cbd.csair.com", "NEWCBDCCSWebServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.79.0.101:8180/CBDCCSWebService/services/NEWCBDCCSWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NEWCBDCCSWebService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.79.0.101:8180/CBDCCSWebService/services/NEWCBDCCSWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NEWCBDCCSWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NEWCBDCCSWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NEWCBDCCSWebService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public NEWCBDCCSWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NEWCBDCCSWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NEWCBDCCSWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns NEWCBDCCSWebServicePortType
     */
    @WebEndpoint(name = "NEWCBDCCSWebServiceHttpPort")
    public NEWCBDCCSWebServicePortType getNEWCBDCCSWebServiceHttpPort() {
        return super.getPort(NEWCBDCCSWebServiceHttpPort, NEWCBDCCSWebServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NEWCBDCCSWebServicePortType
     */
    @WebEndpoint(name = "NEWCBDCCSWebServiceHttpPort")
    public NEWCBDCCSWebServicePortType getNEWCBDCCSWebServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(NEWCBDCCSWebServiceHttpPort, NEWCBDCCSWebServicePortType.class, features);
    }

}
