
package com.csair.b2c.cloud.test.sys.cbd;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-08-27T14:42:39.209+08:00
 * Generated source version: 3.2.6
 */

@WebFault(name = "WebServiceException", targetNamespace = "http://web.service.newccs.cbd.csair.com")
public class WebServiceException_Exception extends Exception {

    private WebServiceException webServiceException;

    public WebServiceException_Exception() {
        super();
    }

    public WebServiceException_Exception(String message) {
        super(message);
    }

    public WebServiceException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public WebServiceException_Exception(String message, WebServiceException webServiceException) {
        super(message);
        this.webServiceException = webServiceException;
    }

    public WebServiceException_Exception(String message, WebServiceException webServiceException, Throwable cause) {
        super(message, cause);
        this.webServiceException = webServiceException;
    }

    public WebServiceException getFaultInfo() {
        return this.webServiceException;
    }
}
