spring:
  application:
    name: b2c-cloud-test-boot
  profiles:
    active: ${active.profile.name}
  thymeleaf:
    cache: false
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    nonSecurePort: ${server.port:8080}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
server:
  port: 8100
management:
  context-path: /actua
  security:
    enabled: false
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}