spring:
  application:
    name: b2c-cloud-test-admin
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    nonSecurePort: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
server:
  port: 9680
management:
  security:
    enabled: false
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}