server:
  port: 8008
spring:
  application:
    name: b2c-cloud-test-mail
  profiles:
    active: ${active.profile.name}
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    nonSecurePort: ${server.port}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  security:
    enabled: false
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}
  ip: ${spring.cloud.client.ipAddress}
  profile: ${active.profile.name}
  system: ${os.name}