server:
  port: 9998
spring:
  application:
    name: b2c-cloud-test-dubbo-provider
dubbo:
  application:
    name: b2c-cloud-test-dubbo-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 21899
  scan:
    basePackages: com.csair.b2c
#  profiles:
#    active: dev
management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    nonSecurePort: ${server.port}
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    healthCheck:
      enabled: true
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}