server:
  port: 8999
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    leaseExpirationDurationInSeconds: 10000
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
spring:
  application:
    name: b2c-cloud-test-sys
  devtools:
    remote:
      secret: syssecret
management:
  security:
    enabled: false
endpoints:
  shutdown:
    enabled: true
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}