server:
  port: 9998
spring:
  application:
    name: b2c-dubbo-server
dubbo:
  application:
    name: b2c-dubbo-server
  registry:
    address: zookeeper://192.168.240.3:2181
  protocol:
    name: dubbo
    port: 21899
  scan:
    basePackages: org.javamaster.b2c