spring:
  application:
    name: b2c-cloud-test-mybatis
  profiles:
    active: ${active.profile.name}
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    nonSecurePort: ${server.port}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  security:
    enabled: false
server:
  port: 9443
  # keytool -genkey -alias tomcat  -storetype PKCS12 -keyalg RSA -keysize 2048  -keystore keystore.p12 -validity 3650
  # 执行成功以后会在目录下生成一个PKCS12格式的命名为keystore.p12的证书文件
  # 注意配置maven resources插件不要过滤此文件
  ssl:
    key-store: classpath:keystore.pfx
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat
http:
  port: 9700
logging:
  level:
    root: INFO
    #org.hibernate: DEBUG
    com.csair.b2c.test.mybatis.mapper: DEBUG
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}
  author: liang yudong
  email: 375709770@qq.com