###
POST http://localhost:9700/exam/getAll
Content-Type:application/json
Accept: application/json
Token: F97EABD8CEAD29074265E22C92FCAD11

{
  "examType": 1,
  "examCode": "KS0001",
  "delFlag": 0,
  "examStatus": 0
}

###
