spring:
  application:
    name: b2c-cloud-test-rpc
  profiles:
    active: ${active.profile.name}
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    nonSecurePort: ${server.port:8600}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  security:
    enabled: false
server:
  port: 8800
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}