spring:
  application:
    name: b2c-cloud-test-cache
  profiles:
    active: ${active.profile.name}
server:
  port: 8700
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    nonSecurePort: ${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  security:
    enabled: false
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}