spring:
  application:
    name: b2c-cloud-test-feign
  profiles:
    active: ${active.profile.name}
server:
  port: 8300
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    nonSecurePort: ${server.port}
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    leaseRenewalIntervalInSeconds: 5
    #服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    leaseExpirationDurationInSeconds: 15
    preferIpAddress: true
    statusPageUrlPath: /info
    #healthCheckUrlPath: ${server.context-path}/health
  client:
	#eureka client刷新本地缓存时间
	#默认30s
    registryFetchIntervalSeconds: 5
	#eureka客户端ribbon刷新时间
	#默认30s
    ServerListRefreshInterval: 5000
    registerWithEureka: true
    fetchRegistry: true
    #启用完整的健康检查
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
ribbon:
  connectTimeout: 1000
  readTimeout: 5000
management:
  security:
    enabled: false
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}
foo:
  list:
    - name: yudong
      age: 26
    - name: liang
      age: 25
feign.common: 公共配置
---
spring:
  profiles: dev
feign.environment: 开发
---
spring:
  profiles: test
feign.environment: 测试
---
spring:
  profiles: prod
feign.environment: 生产