spring:
  application:
    name: b2c-cloud-test-websocket
  profiles:
    active: ${active.profile.name}
  thymeleaf:
    cache: false
    mode: HTML5
    encoding: UTF-8
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    nonSecurePort: ${server.port:8080}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  security:
    enabled: false      
server:
  port: 9600
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}