spring:
  application:
    name: b2c-cloud-test-mongodb
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    nonSecurePort: ${server.port:8080}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
mongo:
  uri: mongodb://127.0.0.1:27017/B2C
server:
  port: 8700