server:
  port: 8808
spring:
  application:
    name: b2c-cloud-test-kotlin
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    nonSecurePort: ${server.port}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}
  ip: ${spring.cloud.client.ip-address}
  profile: ${active.profile.name}
  system: ${os.name}