spring:
  application:
    name: b2c-cloud-test-mybatistk
  profiles:
    active: ${active.profile.name}
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    nonSecurePort: ${server.port:8600}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  security:
    enabled: false
server:
  port: 9701
logging:
  level:
    #org.hibernate: DEBUG
    com.csair.b2c.cloud.test.mybatistk.mapper: DEBUG
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}
  author: liang yudong
  email: 375709770@qq.com