eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8258
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  application:
    name: b2c-swagger2
user:
  enabled: true
  desc: super administration