server:
  port: 9994
spring:
  application:
    name: b2c-cloud-test-dubbo-consumer
  dubbo:
    application:
      name: b2c-cloud-test-dubbo-consumer
    registry:
      address: zookeeper://127.0.0.1:2181
    scan: com.csair.b2c
eureka:
  instance:
    hostname: eureka.dev.csair.com
    port: 8761
    nonSecurePort: ${server.port}
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    healthCheck:
      enabled: true
info:
  service-name: ${spring.application.name}
  packagetime: ${packagetime}